package com.example.ticketingproject.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

import static com.example.ticketingproject.common.util.Constants.*;

@Getter
@AllArgsConstructor
public enum ErrorStatus {
    LOGIN_FAILED(HttpStatus.BAD_REQUEST, "400_LOGIN_FAILED", MSG_LOGIN_FAILED),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "401_INVALID_TOKEN", MSG_INVALID_TOKEN),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "401_TOKEN_EXPIRED", MSG_TOKEN_EXPIRED),
    INVALID_SIGNATURE(HttpStatus.UNAUTHORIZED, "401_INVALID_SIGNATURE", MSG_INVALID_SIGNATURE),
    DUPLICATE_EMAIL(HttpStatus.BAD_REQUEST, "400_DUPLICATE_EMAIL", MSG_DUPLICATE_EMAIL),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "404_USER_NOT_FOUND", MSG_USER_NOT_FOUND),
    ADMIN_NOT_FOUND(HttpStatus.NOT_FOUND, "404_ADMIN_NOT_FOUND", MSG_ADMIN_NOT_FOUND),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST, "400_INVALID_PASSWORD", MSG_INVALID_PASSWORD),
    ALREADY_DELETED_USER(HttpStatus.GONE, "410_ALREADY_DELETED_USER", MSG_ALREADY_DELETED_USER),
    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_REVIEW_NOT_FOUND),
    VENUE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_VENUE_NOT_FOUND),
    SEAT_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_SEAT_NOT_FOUND),
    SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_SESSION_NOT_FOUND),
    SEAT_GRADE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_SEAT_GRADE_NOT_FOUND),
    PERFORMANCE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_PERFORMANCE_NOT_FOUND", MSG_PERFORMANCE_NOT_FOUND),
    DUPLICATE_SESSION(HttpStatus.CONFLICT, "409_DUPLICATE_SESSION", MSG_DUPLICATE_SESSION),
    WORK_NOT_FOUND(HttpStatus.NOT_FOUND, "404_WORK_NOT_FOUND", MSG_WORK_NOT_FOUND),
    CAST_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "404_CAST_MEMBER_NOT_FOUND", MSG_CAST_MEMBER_NOT_FOUND),
    LIKE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_LIKE_NOT_FOUND", MSG_LIKE_NOT_FOUND),
    ACCESS_FORBIDDEN(HttpStatus.FORBIDDEN, "403_ACCESS_FORBIDDEN", MSG_ACCESS_FORBIDDEN),
    LIKE_ALREADY_EXISTS(HttpStatus.CONFLICT, "409_LIKE_ALREADY_EXISTS", MSG_LIKE_ALREADY_EXISTS),
    RESERVATION_NOT_FOUND(HttpStatus.NOT_FOUND, "404_RESERVATION_NOT_FOUND", "존재하지 않는 예약입니다."),
    ALREADY_RESERVED_SEAT(HttpStatus.BAD_REQUEST, "400_ALREADY_RESERVED_SEAT", MSG_ALREADY_RESERVED_SEAT),
    INVALID_RESERVATION_STATUS(HttpStatus.BAD_REQUEST, "400_INVALID_RESERVATION_STATUS", "변경 불가능한 상태입니다."),
    SEAT_CAPACITY_EXCEEDED(HttpStatus.BAD_REQUEST, "400_SEAT_CAPACITY_EXCEEDED", MSG_SEAT_CAPACITY_EXCEEDED),
    SEAT_GRADE_CAPACITY_EXCEEDED(HttpStatus.BAD_REQUEST, "400_SEAT_GRADE_CAPACITY_EXCEEDED", MSG_SEAT_GRADE_CAPACITY_EXCEEDED),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "400_VALIDATION_ERROR", MSG_VALIDATION_ERROR),
    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "404_PAYMENT_NOT_FOUND", MSG_PAYMENT_NOT_FOUND),
    ALREADY_CANCELLED_RESERVATION(HttpStatus.GONE, "410_ALREADY_CANCELLED_RESERVATION", MSG_ALREADY_CANCELLED_RESERVATION),
    ALREADY_PAID_RESERVATION(HttpStatus.GONE, "410_ALREADY_PAID_RESERVATION", MSG_ALREADY_PAID_RESERVATION),
    INSUFFICIENT_BALANCE(HttpStatus.BAD_REQUEST, "400_INSUFFICIENT_BALANCE", MSG_INSUFFICIENT_BALANCE),
    ALREADY_SOLD_SEAT(HttpStatus.BAD_REQUEST, "400_ALREADY_SOLD_SEAT", MSG_ALREADY_SOLD_SEAT),
    CHAT_ROOM_NOT_FOUND(HttpStatus.NOT_FOUND, "404_CHAT_ROOM_NOT_FOUND", MSG_CHAT_ROOM_NOT_FOUND),
    FORBIDDEN_CHAT_ROOM(HttpStatus.FORBIDDEN, "403_FORBIDDEN_CHAT_ROOM", MSG_FORBIDDEN_CHAT_ROOM),
    CHAT_ROOM_ALREADY_COMPLETED(HttpStatus.BAD_REQUEST, "400_CHAT_ROOM_ALREADY_COMPLETED", MSG_CHAT_ROOM_ALREADY_COMPLETED),

    LOCK_ACQUISITION_FAILED(HttpStatus.CONFLICT, "409_LOCK_ACQUISITION_FAILED", MSG_LOCK_ACQUISITION_FAILED),
    LOCK_TIMEOUT(HttpStatus.REQUEST_TIMEOUT, "408_LOCK_TIMEOUT", MSG_LOCK_TIMEOUT),
    LOCK_RELEASE_FAILED(HttpStatus.BAD_REQUEST, "400_LOCK_RELEASE_FAILED", MSG_LOCK_RELEASE_FAILED),
    LOCK_INTERRUPTED(HttpStatus.INTERNAL_SERVER_ERROR, "500_LOCK_INTERRUPTED", MSG_LOCK_INTERRUPTED),
    CHAT_ROOM_NOT_FOUND(HttpStatus.NOT_FOUND, "404_CHAT_ROOM_NOT_FOUND", MSG_CHAT_ROOM_NOT_FOUND),
    FORBIDDEN_CHAT_ROOM(HttpStatus.FORBIDDEN, "403_FORBIDDEN_CHAT_ROOM", MSG_FORBIDDEN_CHAT_ROOM),
    CHAT_ROOM_ALREADY_COMPLETED(HttpStatus.BAD_REQUEST, "400_CHAT_ROOM_ALREADY_COMPLETED", MSG_CHAT_ROOM_ALREADY_COMPLETED),
    INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST,"400_INVALID_STATUS_TRANSITION",MSG_INVALID_STATUS_TRANSITION);


    private final HttpStatus httpStatus;
    private final String errorCode;
    private final String message;
}