package com.example.ticketingproject.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

import static com.example.ticketingproject.common.util.Constants.*;

@Getter
@AllArgsConstructor
public enum ErrorStatus {
    LOGIN_FAILED(HttpStatus.BAD_REQUEST, "400_LOGIN_FAILED", MSG_LOGIN_FAILED),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "401_INVALID_TOKEN", MSG_INVALID_TOKEN),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "401_TOKEN_EXPIRED", MSG_TOKEN_EXPIRED),
    INVALID_SIGNATURE(HttpStatus.UNAUTHORIZED, "401_INVALID_SIGNATURE", MSG_INVALID_SIGNATURE),
    DUPLICATE_EMAIL(HttpStatus.BAD_REQUEST, "400_DUPLICATE_EMAIL", MSG_DUPLICATE_EMAIL),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "404_USER_NOT_FOUND", MSG_USER_NOT_FOUND),
    ADMIN_NOT_FOUND(HttpStatus.NOT_FOUND, "404_ADMIN_NOT_FOUND", MSG_ADMIN_NOT_FOUND),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST, "400_INVALID_PASSWORD", MSG_INVALID_PASSWORD),
    ALREADY_DELETED_USER(HttpStatus.GONE, "410_ALREADY_DELETED_USER", MSG_ALREADY_DELETED_USER),
    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_REVIEW_NOT_FOUND),
    VENUE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_VENUE_NOT_FOUND),
    SEAT_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_SEAT_NOT_FOUND),
    SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_SESSION_NOT_FOUND),
    SEAT_GRADE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_REVIEW_NOT_FOUND", MSG_SEAT_GRADE_NOT_FOUND),
    PERFORMANCE_NOT_FOUND(HttpStatus.NOT_FOUND, "404_PERFORMANCE_NOT_FOUND", MSG_PERFORMANCE_NOT_FOUND),
    DUPLICATE_SESSION(HttpStatus.CONFLICT, "409_DUPLICATE_SESSION", MSG_DUPLICATE_SESSION),
    WORK_NOT_FOUND(HttpStatus.NOT_FOUND, "404_WORK_NOT_FOUND", MSG_WORK_NOT_FOUND),
    CAST_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "404_CAST_MEMBER_NOT_FOUND", MSG_CAST_MEMBER_NOT_FOUND),
    RESERVATION_NOT_FOUND(HttpStatus.NOT_FOUND, "404_RESERVATION_NOT_FOUND", "존재하지 않는 예약입니다."),
    ALREADY_RESERVED_SEAT(HttpStatus.BAD_REQUEST, "400_ALREADY_RESERVED_SEAT", "이미 예약된 좌석입니다."),
    INVALID_RESERVATION_STATUS(HttpStatus.BAD_REQUEST, "400_INVALID_RESERVATION_STATUS", "변경 불가능한 상태입니다."),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "400_VALIDATION_ERROR", MSG_VALIDATION_ERROR);

    private final HttpStatus httpStatus;
    private final String errorCode;
    private final String message;
}